
fct=@(x,y)log(2.*x+y);
a=1.2,b=3,c=1,d=1.6
Integrala=((b-a).*(d-c)/16).*(fct(a,c)+fct(a,d)+fct(b,c)+fct(b,d) ...
    +2.*fct((a+b)/2,c)+2.*fct((a+b)/2,d) ...
    +2.*fct(a,(c+d)/2)+2.*fct(b,(c+d)/2) ...
    +4.*fct((a+b)/2,(c+d)/2))